### ISSUE TITLE
Advanced Model validation tests

### ISSUE THREAD

**Issue by rburghol** [respec/HSPsquared#143]
### Overview
Develop specific performance (accuracy, and/or efficiency) testing of hsp2 model runs.  Extends work #135 
- base is test10  https://github.com/respec/HSPsquared/tree/master/tests/test10/HSP2results
- existing tests verify that:
   - `hsp2 import` completes correctly
   - `hsp2 run` completes without error
- Test should verify:
   - Assert that run data in a given output in `test10.h5` is simulated correctly, like
     - Mean, median, min Q??
      - ?

#### Tasks:
- [x] Develop accuracy tests for test10
- [x] ~~(will not do for the time being) Develop working install for `environment_dev.yml` (see https://github.com/respec/HSPsquared/blob/dependency_options/environment_dev.yml)~~

#### Install `pytest` etc.
```
pip install -e .[dev] # make sure test dependencies are installed
pip install pytest-xdist # allow running tests in parallel
pip install pytest-cov # permit more verbose/detailed tests

```

#### Compare Outputs from test10.uci and test10specl.uci
Basic testing in `HSPsquared/tests/` (from @PaulDudaRESPEC @austinorr)
- Run code without numba: `NUMBA_DISABLE_JIT=1 hsp2 run test10specl.h5`
- Run quick test: `pytest -k test_case`
- Run comparison btwn hsp2 and hspf: `pytest -k test_case -n 2`
- Show every line of code not hit (requires `pytest-cov`): `NUMBA_DISABLE_JIT=1 pytest -k test_case --cov --cov-branch --cov-report term-missing`

#### Very simple pytest
- when a test file is loaded, functions in that file prefixed with `test_` will be automatically executed.
```
import pytest
import os

def test_h5_file_exists():
    assert os.path.exists('test10.h5')

# This shows how how to break the test
def test_that_should_fail():
    assert os.path.exists('nonexistent_h5_file.h5')
```

**Comment by rburghol** [comment]
@austinorr I am trying to run the test_regression.py on my local install, and am failing on the import line `from .convert.regression_base import RegressTest as RegressTestBase`

~~Can you help me locate this?  I can't see where to obtain such a thing. Thanks in advance!~~
ACtually I just realized that if I run from the "tests" folder, then change the statement to `from convert.reg...` it works fine.  Now I am wondering if this is a synax different between my linux install and whatever platform the github testing suite runs on...  insights welcome

**Comment by austinorr** [comment]
@rburghol you should be able to undo those changes if you run `pytest` from the top of the repo like so:

```prompt
(hsp2) ~/source/hsp2$ pytest -k test_regression 
================================================================================================== test session starts ==================================================================================================
platform linux -- Python 3.11.14, pytest-9.0.0, pluggy-1.6.0
rootdir: /home/aorr/wsl-sources/hsp2
configfile: pyproject.toml
collected 4 items / 2 deselected / 2 selected                                                                                                                                                                           

tests/test_regression.py ..
```

**Comment by rburghol** [comment]
@austinorr thanks so much for the quick response.  I do that and get a similar output to you, so I think that's a good sign.  I loads the hdf5, runs the model and commences testing.
```
pytest -k test_regression
=================================================== test session starts ====================================================
platform linux -- Python 3.9.5, pytest-8.4.2, pluggy-1.6.0
rootdir: /opt/model/HSPsquared
configfile: pyproject.toml
plugins: xdist-3.8.0, cov-7.0.0
collected 4 items / 2 deselected / 2 selected
...
134 reading from wdm
135 reading from wdm
136 reading from wdm
140 reading from wdm
2026-01-10 13:59:53.97   Processing started for file /opt/model/HSPsquared/tests/test10specl/HSPFresults/test10specl.h5; saveall=True
STATE initializing contexts.
================================================= short test summary info ==================================================
FAILED tests/test_regression.py::test_case[test10specl] - KeyError: '/STATE/timer'
================================== 1 failed, 1 passed, 2 deselected in 141.46s (0:02:21) ===================================
/
```
Now, that accomplished, I see `KeyError: '/STATE/timer'` -- the error that shows when the testing is executed on github (Note: github testing process [error](https://github.com/respec/HSPsquared/actions/runs/20860244981/job/59937734415?pr=202) from the [PR](https://github.com/respec/HSPsquared/pull/202/)). So, now, my goal is to be able to step my way through this so that I can determine what's going on.   .
I did:
- Run the test (from base HSPsquared directory) 
   - `python3`
```
import tests.test_regression
tests.test_regression.test_case("test10specl")`

```
- Which succeeds in loading the `h5`, then running `hsp2`, then provides tons of output:
```
    PERLND_001  PWTGAS  SOCO2

    PERLND_001  PWTGAS  IODOX
...
    IMPLND_001  IQUAL  SOQOCOD

    IMPLND_001  IQUAL  SOQUALCOD

```
Which is all excellent progress, however, I see no record of the error -- any ideas if there is some kind of next step I should be pursuing?
