### ISSUE TITLE
UCI import with 15min timestep

### ISSUE THREAD

**Issue by trees4me** [respec/HSPsquared#22]
Hi,
I have a UCI file that runs at 15min timestep. A couple issues have come up running the import checks, but I'm still unable to reproduce HSPF results.

Issues:
1)  external sources evap record is 15-min with a 0.75 multiplier in HSPF.  The MFACTOR comes into HSP2 ok, but needs to be divided by 96 (=4*24).  After revising this MFACTOR the IMPLND and portions of the PERLND are ok.

2) The PERLND in HSP2 are not reproducing HSPF results. I've traced the source to the groundwater storage bin (AGWS/AGWO).  Everything above that is nearly identical.  The AGWI is nearly identical for HSP2 vs HSPF.
![perlnd_p211_pwater_agwi](https://user-images.githubusercontent.com/35086910/51899915-df36eb00-2368-11e9-96d7-8dbe15fb0fd0.png)

However, the AGWO, AGWS, and GWVS all vary between HSP2 and HSPF.  I checked all the PERLND parameters and states and they are the same.  Evap is off on the groundwater bin (AGWET=BASET=0).  

![perlnd_p211_pwater_agwo](https://user-images.githubusercontent.com/35086910/51900254-b4996200-2369-11e9-8348-5c454e6ec547.png)
![perlnd_p211_pwater_agws](https://user-images.githubusercontent.com/35086910/51900255-b4996200-2369-11e9-8457-83adb44484c1.png)

Trying to figure out what to try next.  KGW appears to be 0 (AGWRC=0.997, DELT60=0.25 for 15min), and perhaps HSP2 is treating this case differently than HSPF?  Is something else different about the groundwater routine?  Perhaps the 15-min time step may be an issue here as it was with item 1.
Any ideas are appreciated.
Thanks.

**Comment by JasonLoveRespec** [comment]
Thanks for the detailed explanation of the issue.  We will look into and get back to you with any information.

JASON LOVE, P.E.
Senior Vice President

605.394.6512 office // 605.484.2380 cell
________________________________

**Comment by trees4me** [comment]
I did a quick test with DELT=60min and the perlnds/implnds are ok.  It's appears to be an issue related to the 15min time step, where KGW trends to 0.  At 60min DELT the KGW value is non-0.

Thanks
-Pat 

perlnd comparison table HSP2 (60min) vs HSPF (15min), reasonable monthly results.

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Max Diff</th>
      <th>Sum of HSPF</th>
      <th>Sum of HSP2</th>
      <th>%diff of Sum</th>
      <th>abs(%diff of Sum)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>274</th>
      <td>1.36</td>
      <td>547.93</td>
      <td>548.01</td>
      <td>-0.01</td>
      <td>0.01</td>
    </tr>
    <tr>
      <th>241</th>
      <td>1.45</td>
      <td>534.70</td>
      <td>534.28</td>
      <td>0.08</td>
      <td>0.08</td>
    </tr>
    <tr>
      <th>242</th>
      <td>1.45</td>
      <td>533.44</td>
      <td>533.02</td>
      <td>0.08</td>
      <td>0.08</td>
    </tr>
    <tr>
      <th>243</th>
      <td>1.45</td>
      <td>532.21</td>
      <td>531.77</td>
      <td>0.08</td>
      <td>0.08</td>
    </tr>
    <tr>
      <th>244</th>
      <td>1.45</td>
      <td>530.87</td>
      <td>530.42</td>
      <td>0.08</td>
      <td>0.08</td>
    </tr>
    <tr>
      <th>273</th>
      <td>1.30</td>
      <td>514.84</td>
      <td>514.28</td>
      <td>0.11</td>
      <td>0.11</td>
    </tr>
    <tr>
      <th>231</th>
      <td>1.43</td>
      <td>505.02</td>
      <td>504.26</td>
      <td>0.15</td>
      <td>0.15</td>
    </tr>
    <tr>
      <th>233</th>
      <td>1.40</td>
      <td>500.49</td>
      <td>499.73</td>
      <td>0.15</td>
      <td>0.15</td>
    </tr>
    <tr>
      <th>234</th>
      <td>1.41</td>
      <td>499.73</td>
      <td>498.96</td>
      <td>0.15</td>
      <td>0.15</td>
    </tr>
    <tr>
      <th>232</th>
      <td>1.43</td>
      <td>504.22</td>
      <td>503.44</td>
      <td>0.15</td>
      <td>0.15</td>
    </tr>
    <tr>
      <th>284</th>
      <td>1.36</td>
      <td>435.23</td>
      <td>434.46</td>
      <td>0.18</td>
      <td>0.18</td>
    </tr>
    <tr>
      <th>211</th>
      <td>1.03</td>
      <td>401.23</td>
      <td>400.39</td>
      <td>0.21</td>
      <td>0.21</td>
    </tr>
    <tr>
      <th>272</th>
      <td>1.23</td>
      <td>460.03</td>
      <td>458.95</td>
      <td>0.23</td>
      <td>0.23</td>
    </tr>
    <tr>
      <th>221</th>
      <td>1.33</td>
      <td>452.18</td>
      <td>451.07</td>
      <td>0.24</td>
      <td>0.24</td>
    </tr>
    <tr>
      <th>212</th>
      <td>1.12</td>
      <td>417.38</td>
      <td>416.35</td>
      <td>0.25</td>
      <td>0.25</td>
    </tr>
    <tr>
      <th>222</th>
      <td>1.36</td>
      <td>462.33</td>
      <td>461.17</td>
      <td>0.25</td>
      <td>0.25</td>
    </tr>
    <tr>
      <th>223</th>
      <td>1.32</td>
      <td>454.83</td>
      <td>453.68</td>
      <td>0.25</td>
      <td>0.25</td>
    </tr>
    <tr>
      <th>224</th>
      <td>1.33</td>
      <td>454.92</td>
      <td>453.76</td>
      <td>0.25</td>
      <td>0.25</td>
    </tr>
    <tr>
      <th>271</th>
      <td>1.12</td>
      <td>415.12</td>
      <td>414.07</td>
      <td>0.25</td>
      <td>0.25</td>
    </tr>
    <tr>
      <th>213</th>
      <td>1.28</td>
      <td>441.69</td>
      <td>440.51</td>
      <td>0.27</td>
      <td>0.27</td>
    </tr>
    <tr>
      <th>214</th>
      <td>1.36</td>
      <td>464.83</td>
      <td>463.58</td>
      <td>0.27</td>
      <td>0.27</td>
    </tr>
    <tr>
      <th>283</th>
      <td>1.24</td>
      <td>401.24</td>
      <td>400.12</td>
      <td>0.28</td>
      <td>0.28</td>
    </tr>
    <tr>
      <th>282</th>
      <td>1.10</td>
      <td>382.03</td>
      <td>380.94</td>
      <td>0.29</td>
      <td>0.29</td>
    </tr>
    <tr>
      <th>285</th>
      <td>1.10</td>
      <td>382.03</td>
      <td>380.94</td>
      <td>0.29</td>
      <td>0.29</td>
    </tr>
    <tr>
      <th>281</th>
      <td>1.13</td>
      <td>384.55</td>
      <td>383.40</td>
      <td>0.30</td>
      <td>0.30</td>
    </tr>
  </tbody>
</table>

**Comment by aufdenkampe** [comment]
@trees4me, although you posted this issue 2 years ago, it might be of interest that there's been renewed work on this in the last 6-9 months, as tracked with #40.  

If you are still using this, or interested in helping us test, some of the more recent updates discussed there are still on the `develop` branch.

**Comment by aufdenkampe** [comment]
Closing this issue as it's now been implemented with closing of #40.
