### ISSUE TITLE
Fixed limits on operation is all solved in HSP2?

### ISSUE THREAD

**Issue by scalet98** [respec/HSPsquared#24]
As long as I know, fortran version HSPF has a limited no. of operation.
Therefore, there was a limitation on the application of LULC or Reach. 
According to your program specification, there were no more fixed limits on operations. 

    " Restructure for maintainability, to remove fixed limits (e.g., operations, land use,
       parameters), and to maintain or improve execution time."

Then we don't need to construct the model separately
due to the functional limitation when applying HSP2. 
Right? 

Best regards. 
Jiheon Lee.

**Comment by JasonLoveRespec** [comment]
There is not a functional (fixed number of operations) limitation.  There is still a practical reason to divide the model up into a logical number of operations.

JASON LOVE, P.E.
Senior Vice President

605.394.6512 office // 605.484.2380 cell

________________________________

**Comment by scalet98** [comment]
Hello!~ JASON !

Thank you for your kind and quick reply.
I understand what you mean.
Last time, while constructing the model, I have faced difficulties due to the limitations of operation.
At first time, I did not know that there was limited no. of operation is possible in HSPF model.

Anyhow, now your HSP2 does not have any limitations on it.
I welcome HSP2.
I don't need to separate the model intentionally, as long as I use HSP2.
For sure, I will divide the model it is required logically.

Thank you again.

Jiheon Lee


________________________________

Ji-Heon Lee
Ph. D. Candidate
Dep. of Urban Engineering
Chungbuk National University

Tel : +82-43-275-3478
Fax : +82-43-275-3478
Cellphone : +82-10-2745-2316
E-mail : career03@hotmail.com<http://mail2.daum.net/hanmail/mail/MailComposeFrame.daum?TO=career03%40hotmail.com>

________________________________
보낸 사람: Jason Love <notifications@github.com>
보낸 날짜: 2019년 3월 28일 목요일 오후 8:51
받는 사람: respec/HSPsquared
참조: Jiheon Scarlett Lee; Author
제목: Re: [respec/HSPsquared] Fixed limits on operation is all solved in HSP2? (#24)

There is not a functional (fixed number of operations) limitation. There is still a practical reason to divide the model up into a logical number of operations.

JASON LOVE, P.E.
Senior Vice President

605.394.6512 office // 605.484.2380 cell

________________________________
