### ISSUE TITLE
Working environment for HSPsquared ?

### ISSUE THREAD

**Issue by scalet98** [respec/HSPsquared#26]
What is the Working environment for HSPsquared?
Is it only workable in Python 2.7 condition? 
Actually, I have installed Python 3.7.3 and when applying HSPsqured code as YouTube material presented, It shows error condition continuously. 

Could you help me out what the problem is? 
Attached is a pic of screenshot :) 

Thanks. 

![12](https://user-images.githubusercontent.com/48939258/73632730-04f38000-46a0-11ea-9074-ddde12783a5e.png)

**Comment by JasonLoveRespec** [comment]
We are nearing a release for Python 3; for current GitHub version you will need to use Python 2.x.

JASON LOVE, P.E.
Senior Vice President

605.394.6512 office // 605.484.2380 cell
________________________________

**Comment by scalet98** [comment]
When could I expect to apply those version?
Could you give me approximate month for the release of those version ? 
Looking forward to having good news. 

Jiheon Lee.
