### ISSUE TITLE
ViewRCHRES - change 'get_store' to 'HDFStore'

### ISSUE THREAD

**Issue by jlkittle** [respec/HSPsquared#3]
in ViewRCHRES the statement `with` pd.get_store(hdfname, mode='r') as store:'
results in the following message
    'sys:1: FutureWarning: get_store is deprecated and be removed in a future version
    HDFStore(path, **kwargs) is the replacement'

also, remove 'mode='r' in argument list as HDF5 file may already be open

**Comment by PaulDudaRESPEC** [comment]
Closing since this one is related to the old python 2 notebooks
