### ISSUE TITLE
Converting error from WDM to HDF5 file format with own dataset. 

### ISSUE THREAD

**Issue by scalet98** [respec/HSPsquared#37]
Hello !  
Currently, I am trying to apply your code with my dataset. 
So for now, I am trying to converting wdm file to HDF5 format. 

_**After I applying my own dataset**_ (as a test I used BASINS4 sample sediment dataset which is mostly larger dataset(56timeseries) than your test01 code(19timeseries)) _**with your ReadWDM module, I have got an error as below picture shows.**_ 

![106986773_644429486148620_1507050922593792267_n](https://user-images.githubusercontent.com/48939258/86675405-9478d280-c034-11ea-8ed5-e28b22b6978f.jpg)

**Point-1** 
- Do you have any specific rules, when we are developing wdm file format to apply your HDF5 converter? 

**Point-2**
- Now I am reviewing your ReadWDM file code. 
- But until now I could not find any troubled line. 
- Eventhough some lines are questionable due to the some number you are using to develop the codes. But for now, I do not have detailed WDM DB specification for variables. 
- For reference, **_could you share the original WDM database table or column specifications for variables?_** Then It would be easier task I think. 

If you know why it is coming up. Please let me know.  
Thank you for developing this package and reading this question. 

Jiheon Lee.

**Comment by PaulDudaRESPEC** [comment]
I think the issue is related to the WDM attributes available on those data sets.  It seems to me the ReadWDM code looks for this list of attributes:
search = ['STAID', 'STNAM', 'SCENARIO', 'CONSTITUENT','LOCATION']
If it finds any of them, it expects the same set to exist for all the data sets.  

A quick work-around might be to add the missing attributes so that the same set exists for each timeseries in the WDM file.

**Comment by scalet98** [comment]
PaulDuda ! Thank you ! 
Unexpectedly, solution is too simple. 
I was too serious about the issue I think. 
I checked out every single line in the code. 

Always, Simple is the best way !~ 
Thank you again ! 

> I think the issue is related to the WDM attributes available on those data sets. It seems to me the ReadWDM code looks for this list of attributes:
> search = ['STAID', 'STNAM', 'SCENARIO', 'CONSTITUENT','LOCATION']
> If it finds any of them, it expects the same set to exist for all the data sets.
> 
> A quick work-around might be to add the missing attributes so that the same set exists for each timeseries in the WDM file.

**Comment by PaulDudaRESPEC** [comment]
Glad I could help!  
I believe it is an issue to be fixed, in that it should not be a requirement that there be the same set of attributes on each WDM timeseries data set.

**Comment by scalet98** [comment]
Hello !~ PaulDuda ! 

I have one more question. 
**_In the ReadWDM file, you are using the number 512 in the code line 37._** ( I have attached the related pic with red line marker below)
- It seems like that you are using 512, when you are identifying the times series starting index. For instance, first series times series starts from index no. = 512, and second one starts from 512*n and so on. But here is the question. 
*** **_Where does the number 512 come from?_** 

- It seems like that the no. comes from **_the WDM DB/ Table specification which defines the specifications including ID, DSN, and etc. for WDM DB variables_**. If that is the case _**Could you send me one of this or could you let me know the source of it?**_ 

- **_Sorry for bothering you again._** Even though, I have resolved the issue this time, I would like to understand the what the code lines say exactly for further application. 

Thank you for reading the comments again !~ 

Best regards, 
Jiheon Lee 

![code](https://user-images.githubusercontent.com/48939258/86982437-324ed780-c1c4-11ea-8caf-71b986f8b632.png)

**Comment by PaulDudaRESPEC** [comment]
I believe the 512 is the record length in the WDM file, but I'm at the limit of my knowledge in that territory.  Someone else on the team may have to answer the follow-on questions.

**Comment by scalet98** [comment]
Hello ! PaulDuda !

Thank you for your kind reply. 
It was not my territory either, but I just want to understand the code thoroughly. 

I think I need to upload the question again or contact the code designer directly. 
Thank you ! 

Jiheon Lee. 

> I believe the 512 is the record length in the WDM file, but I'm at the limit of my knowledge in that territory. Someone else on the team may have to answer the follow-on questions.
