### ISSUE TITLE
Running HSP2 from console in Linux

### ISSUE THREAD

**Issue by rburghol** [respec/HSPsquared#39]
I am trying to explore the possibility of running hsp2 from the console in Linux -- anyone done this?  I am thinking similar to how the old hspf version would be run where one supplies a uci name and execution flows from there.

**Comment by PaulDudaRESPEC** [comment]
You might look at HSP2_Driver.py as a starting point.  I put that together a while ago to be able to run HSP2 from my preferred development environment.  It prompts you for the name of the HDF5 or UCI file as input and runs the simulation, and it also allows the name of the input file on the command line.

**Comment by rburghol** [comment]
Thanks @PaulDudaRESPEC !

**Comment by aufdenkampe** [comment]
This looks resolved. Feel free to reopen if it isn't working for you.
