### ISSUE TITLE
Write WDM?

### ISSUE THREAD

**Issue by rburghol** [respec/HSPsquared#54]
Wondering if there is code in this suite for writing WDM files?  I still use wdimex written in fortran, but if there is a modern implementation in this package I may adopt.

**Comment by PaulDudaRESPEC** [comment]
HSPSquared includes a robust WDM reader, for importing time series data from WDM into HDF5, but the results of HSPSquared stay in HDF5, i.e. they are not written back to WDM.  If there's interest and resources, we'd be happy to work with you to create that capability!
