### ISSUE TITLE
Error in Preview.ipynb, Step 15

### ISSUE THREAD

**Issue by ethankale** [respec/HSPsquared#6]
The Preview Jupyter notebook throws an error on Cell 15:

`df = HSP2.readPLTGEN(pltname)`
`df.head()`

`---------------------------------------------------------------------------`
`AttributeError                            Traceback (most recent call last)`
`<ipython-input-15-1f9059be498a> in <module>()`
`----> 1 df = HSP2.readPLTGEN(pltname)`
`      2 df.head()`

`AttributeError: 'module' object has no attribute 'readPLTGEN'`

**Comment by JasonLoveRespec** [comment]
Nat - thanks for correcting this error.  We had initially had numerous "helper" functions embedded into HSP2 but subsequently moved into HSP2tools as you indicated.  The Preview Notebook was an initial notebook I developed and ultimately migrated to the Introduction.  I meant to remove but it was pushed up to the site.  We also changed a couple other things that make the Preview Notebook incorrect for Section 4.  Im going to remove it from the repo.
