### ISSUE TITLE
Read access to repo?

### ISSUE THREAD

**Issue by ethankale** [respec/HSPsquared#8]
I would like to submit pull requests for simple stuff like fixing deprecation warnings in the tutorials.  To do that I need to keep my fork synced with the main repo, and to do THAT I need to be able to read from the repo (see https://help.github.com/articles/syncing-a-fork/).  Looks like clone/read rights are locked down at the moment.  

Are you guys accepting updates/changes/fixes right now?

**Comment by aufdenkampe** [comment]
Closing, as we've had read access since at least early 2020.

If you are still interested in using HSP2, we're been and will continue actively developing it. We would love to build an active community of users and contributors.
