### ISSUE TITLE
qrid.enable() is not an available command

### ISSUE THREAD

**Issue by mishranurag** [respec/HSPsquared#9]
I get the following error when I run 
## Required Python imports  and setup
cell.

AttributeError: 'module' object has no attribute 'enable'

**Comment by JasonLoveRespec** [comment]
Did you install qgrid ... https://github.com/quantopian/qgrid.

**Comment by mishranurag** [comment]
I was finally able to install qgrid. It was a multiple step process. Thanks for the link. I had to install using this command 
    conda install -c tim_shawver qgrid
And then I had to enable the nbextentions.
